# Generated by Django 4.2.7 on 2024-03-11 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dese', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='realshop/categories')),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dese', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='realshop/propertys')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bookingprice', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stock', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='renthome.category')),
            ],
        ),
    ]
